### ISSUE TITLE
I still arrive at a fresh looking laravel 6 installation after the steps 

### ISSUE THREAD

**Issue by Yusuf-Kolayo** [venturedrake/laravel-crm#24]
- Laravel CRM Version: #.#.#
- PHP Version: 7.2

### Description:
i still arrive at a fresh looking installation of laravel 6 after taking time to follow all steps from 1 to 7 , every step went through without errors , when i do not know how to access the app since you do not provide a username and password , i registered a new user and logged in , what i still arrive at was like i never pass through the steps at all ?!? Below is my screenshot. Please help me think of what could be wrong ...

### Steps To Reproduce:
1 to 7
![crm](https://user-images.githubusercontent.com/68844432/114254333-93e7e080-99a6-11eb-9100-641a32009492.PNG)

**Comment by Yusuf-Kolayo** [comment]
here is a screenshot of my code environment
![crm2](https://user-images.githubusercontent.com/68844432/114254406-17093680-99a7-11eb-927c-34e982d60b13.PNG)

**Comment by andrewdrake** [comment]
Hi @Yusuf-Kolayo,

Sorry I haven't completed the docs yet, and I can see how this might happen. There are a few different ways the package is installed, depending on the use case. 

When you are logged in, can you access this url? http://your-project-name/crm

Just add the /crm to  the url you use to access the installation. 

Andrew

**Comment by Yusuf-Kolayo** [comment]
Thanks for being fast to reply , i added crm to my url as you pointed out above and was able to access the crm!

**Comment by andrewdrake** [comment]
No problem @Yusuf-Kolayo 

The package is under some heavy development at the moment, keep an eye on updates as they will be coming through often as I work towards a production ready version 1 release!

Andrew
