### ISSUE TITLE
Is it stilll not ready for production

### ISSUE THREAD

**Issue by ugintl** [venturedrake/laravel-crm#31]
Can it be used in production?

**Comment by andrewdrake** [comment]
Just an update, closing this task but production release is coming soon. Sorry for delay, some paid projects took priority over the past few months.

**Comment by ugintl** [comment]
@andrewdrake The project page still says that it is not for production use.

**Comment by andrewdrake** [comment]
@ugintl Yes sorry I have been busy with some other projects lately. I'm still working on this project, and in fact are using it already in several projects in production. I will get. back into it soon and still have a goal of a production ready V1 towards end of Sept now.

**Comment by andrewdrake** [comment]
@ugintl Thanks :) Yes can be used 8 or 9, I actually have a few updates coming this and next week as some production projects have pushed for some features
