### ISSUE TITLE
 Class 'App\Models\Team' not found

### ISSUE THREAD

**Issue by shajeerEmiratesZone** [venturedrake/laravel-crm#33]
Laravel 8  composer require venturedrake/laravel-crm:^0.9 shows  Class 'App\Models\Team' not found

**Comment by andrewdrake** [comment]
Thanks for reporting this. Are you using a base Laravel 8 installation or with Jetstream? That class comes from Jetstream and should not be required, so will fix this as a bug.

**Comment by shajeerEmiratesZone** [comment]
Yes I'm using base laravel 8

**Comment by andrewdrake** [comment]
This is now fixed in version 0.10.0 https://github.com/venturedrake/laravel-crm/releases/tag/0.10.0
