### ISSUE TITLE
ERROR : Auth guard [api] is not defined. when running php artisan db:seed --class="VentureDrake\LaravelCrm\Database\Seeders\LaravelCrmTablesSeeder"

### ISSUE THREAD

**Issue by shajeerEmiratesZone** [venturedrake/laravel-crm#34]
Gives an error Auth guard [api] is not defined. while running php artisan db:seed --class="VentureDrake\LaravelCrm\Database\Seeders\LaravelCrmTablesSeeder"
on Laravel 8 fresh install with jetstream

**Comment by andrewdrake** [comment]
Working on it

**Comment by andrewdrake** [comment]
This error is a result of an issue in a vendor package it uses for audit logs, and Laravel updating config for auth. See [https://github.com/owen-it/laravel-auditing/pull/682/commits/cba6ebc472a77ff5847be4ac8a37bd70bfc9399c](url)

**Comment by andrewdrake** [comment]
This is now fixed in version 0.10.0 https://github.com/venturedrake/laravel-crm/releases/tag/0.10.0
