### ISSUE TITLE
403 forbidden after login

### ISSUE THREAD

**Issue by phemorah** [venturedrake/laravel-crm#39]
Please i need someone to help out, I have been getting a "403 forbidden" error upon logging in and right after creating a new user account also.

**Comment by andrewdrake** [comment]
Did you run the seeder? It loads the base set of roles & permissions. 

`php artisan db:seed --class="VentureDrake\LaravelCrm\Database\Seeders\LaravelCrmTablesSeeder"`

**Comment by phemorah** [comment]
Thank you @andrewdrake. I was able to resolve this by simply changing the crm owner to my loggedin email in the config > laravel-crm file directory

**Comment by andrewdrake** [comment]
Ok great
