### ISSUE TITLE
Custom fields are not displaying to any model add or edit

### ISSUE THREAD

**Issue by PeanutSquareLLP** [venturedrake/laravel-crm#58]
- Laravel CRM Version: #.#.#
- PHP Version: 8.2

### Description :
i am trying Laravel CRM demo, and i have implemented Laravel CRM on local. I have added 1 custom field to **deal and lead** from setting. but it is not showing those fields to add or edit action of deal or lead

### Steps To Reproduce:
add custom field to deal 
https://demo.laravelcrm.com/fields/create

then that custom field is not displaying while creating deal
https://demo.laravelcrm.com/deals/create

**Comment by andrewdrake** [comment]
Thanks form reporting, I will be making some updates to get this working. Custom fields are sort of not complete at the moment

**Comment by nishantp306** [comment]
thanks @andrewdrake if you need help let me know i would love to contribute

**Comment by andrewdrake** [comment]
This should now be working in latest version 1.2.2
